systemConfig:
  host: localhost
  port: 9000
  secret: cukor.cn
  issuer: cukor

mysql:
  host: localhost
  port: 3306
  user: root
  password: cukor
  dbname: nourish_orchard
  param: charset=utf8mb4&parseTime=True&loc=Local